### ISSUE TITLE
Missing includes

### ISSUE THREAD

**Issue by codecircuit** [eyalroz/cuda-kat#99]
- `stream.hpp` uses `pool_t` defined in `memory_pool.hpp`
- `memory_pool.hpp` uses `ipc::ptr_handle_t` defined in `ipc.hpp`
- `nvtx/profiling.hpp` uses `scoped_existence_ensurer_t` defined in `api/multi_wrapper_impls/context.hpp`

**Comment by eyalroz** [comment]
Well, this library depends on an older version of cuda-api-wrappers. I should certainly update it :-)

**Comment by codecircuit** [comment]
Apologies. This issue belongs to the cuda API wrappers.

**Comment by codecircuit** [comment]
Created [#515](https://github.com/eyalroz/cuda-api-wrappers/issues/515)
